### PR TITLE
Add support of TLS connections

### PR DESCRIPTION
**Pull request by Onlinehead**
Just little change about support of TLS connections which sometimes useful.
Here is example of using with TLS:
```
amqp_url := "amqps://guest:guest@127.0.0.1:5671/"
cert, err := tls.LoadX509KeyPair("cert.pem", "key.pem")
tls_config := tls.Config{
			Certificates: []tls.Certificate{cert},
			InsecureSkipVerify: true}
cli := cony.NewClient(
		cony.URL(amqp_url),
		cony.Backoff(cony.DefaultBackoff),
		cony.TLS(&tls_config),
	)
```

### CODE REVIEW

**Comment by kron4eg** [comment]
@Onlinehead hello, and thank you for your PR!

I want to suggest couple of things. Please take a look at how `amqp.Dial()` and `amqp.DialTLS()` are implemented. They both use the same `amqp.DialConfig()`, which call actual dial function, and it can handle `amqps://` scheme automatically, so there is no need in

    if c.tlsConf != nil {

So what we can do instead of `cony.TLS()` function is `cony.Config()`, and pass initialized `amqp.Config` in it, which should be used in `amqp.DialConfig` replacing `amqp.Dial` in cony source.

Thank you!

**Comment by Onlinehead** [comment]
@kron4eg Thanks for your tips.
I changed code for using DialConfig and yes, that is pretty better way:)
About checks, that is so strange, because on my PC checks passed without error:

**Comment by kron4eg** [comment]
I wander if it's necessary to provide default Heartbeat in case it's 0, like in original `amqp.Dial()`... It's very easy to forget about it and get strange disconnects.

**Comment by kron4eg** [comment]
LGTM 👍

**Pull request merged**
